### DISCUSSION TITLE
ubuntu中的docker-compose运行的v2raya 不能实现透明代理

### DISCUSSION THREAD

**Discussion by xingshu1990** [v2rayA/v2rayA#1482] [Q&A]
## 环境介绍
主要工作的环境是，有一台微主机装了docker-comopse 运行着Adguardhome 和[paopaodns](https://github.com/kkkgo/PaoPaoDNS)，
Adguardhome占用的端口是：
```
 - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "68:68/udp"
      - "80:80/tcp"
      - "443:443/tcp"
      - "443:443/udp"
      - "3000:3000/tcp"
      - "853:853/tcp"
      - "853:853/udp"
      - "5443:5443/tcp"
      - "5443:5443/udp"
      - "6060:6060/tcp"
```
paopaodns占用的端口是：

```
      - "54:53/tcp"
      - "54:53/udp"
      - "5304:5304/udp"
      - "5304:5304/tcp"
      - "7889:7889/tcp"
```
目前特地在vbox中开了一个ubuntu 装了docker-compose 单独开一个v2raya进行安装测试，等虚拟机中的v2raya 能正常实现透明代理，就安装到软路由中。
docker-compose文件如下：
```
services:
  v2raya:
    image: mzz2017/v2raya
    container_name: v2raya
    restart: always
    privileged: true
    environment:
      - V2RAYA_LOG_FILE=/tmp/v2raya.log
      - V2RAYA_V2RAY_BIN=/usr/local/bin/v2ray
      - V2RAYA_NFTABLES_SUPPORT=off
      - IPTABLES_MODE=legacy
    volumes:
      - /lib/modules:/lib/modules:ro
      - /etc/v2raya:/etc/v2raya
    ports:
      - "2017:2017"
      - "20170-20172:20170-20172"

```
官方的手册中的docker单页里，没有说明v2ray-core、geosite、geoip的下载。
https://v2raya.org/docs/prologue/installation/docker/

遂windown中开着v2rayn，开启youtube找视频，按照视频内容进行调整。

![1](https://github.com/user-attachments/assets/36dfb21f-0de2-4850-abf3-68f459a14536)
![2](https://github.com/user-attachments/assets/a6b51a24-d394-47b0-af3f-ba82dabe1646)
![3](https://github.com/user-attachments/assets/62f1aae6-7afe-470e-b4e1-e99085619851)
如上图所示，docker-compose中的v2raya已经正常运行，
在主电脑上的浏览器的代理设置里，输入ip+端口，浏览器能正常代理访问youtube、google等网站，
但是测试透明代理（将网关改为这个虚拟机的地址），发现任何网站都不能打开。

以下是：sudo iptables -t nat -L -n -v后 返回的内容
![5](https://github.com/user-attachments/assets/cb6e63a5-2ab6-42ab-b770-85857bd36ec3)
