### ISSUE TITLE
k8s中运行报错

### ISSUE THREAD

**Issue by magicJie** [v2rayA/v2rayA#1163]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA
 2.2.4

3. 你通过什么方式安装v2rayA
k8s

5. 你所使用的操作系统
Huawei Cloud EulerOS

### 描述问题

点击“启动”后报错，“failed to start v2ray-core: unexpected exiting: check the log for more information”

### 复现问题的步骤

k8s部署的yaml清单：
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: v2raya
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: v2raya
  template:
    metadata:
      labels:
        app: v2raya
    spec:
      dnsConfig:
        nameservers:
          - 114.114.114.114
      containers:
        - name: v2raya
          image: swr.lan.aiminjie.com/amj/v2raya:latest
          resources:
            limits:
              memory: 100Mi
              cpu: 100m
          ports:
            - containerPort: 2017
            - containerPort: 20170
            - containerPort: 20171
            - containerPort: 20172
          volumeMounts:
            - name: v2raya-config
              mountPath: /etc/v2raya
      volumes:
        - name: v2raya-config
          persistentVolumeClaim:
            claimName: v2raya-config-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: v2raya-config-pvc
  namespace: devops
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
  storageClassName: nfs-client
---
apiVersion: v1
kind: Service
metadata:
  name: v2raya
  namespace: devops
spec:
  selector:
    app: v2raya
  externalIPs:
    - 10.0.1.116
  ports:
    - name: v2raya-main
      port: 2017
      targetPort: 2017
    - name: v2raya-additional-1
      port: 20170
      targetPort: 20170
    - name: v2raya-additional-2
      port: 20171
      targetPort: 20171
    - name: v2raya-additional-3
      port: 20172
      targetPort: 20172

```

### v2rayA/v2ray运行日志：

2023/11/10 08:53:20.918 [I] [main.go:25]  Cannot load TPROXY module: failed to modprobe xt_TPROXY: modprobe: can't change directory to '/lib/modules': No such file or directory
2023-11-10T16:53:20.918261299+08:00 
2023-11-10T16:53:21.124788197+08:00 2023/11/10 08:53:21.124 [A] [main.go:29]  V2Ray binary is /usr/bin/v2ray
2023-11-10T16:53:21.124821023+08:00 2023/11/10 08:53:21.124 [A] [main.go:29]  V2Ray asset directory is /run/user/0/v2raya
2023-11-10T16:53:21.124824282+08:00 2023/11/10 08:53:21.124 [A] [main.go:29]  v2rayA working directory is /root
2023-11-10T16:53:21.124828373+08:00 2023/11/10 08:53:21.124 [A] [main.go:29]  v2rayA configuration directory is /etc/v2raya
2023-11-10T16:53:21.124831835+08:00 2023/11/10 08:53:21.124 [A] [main.go:29]  Golang: go1.21.0
2023-11-10T16:53:21.124835209+08:00 2023/11/10 08:53:21.124 [A] [main.go:29]  OS: linux
2023/11/10 08:53:21.124 [A] [main.go:29]  Arch: amd64
2023-11-10T16:53:21.124840785+08:00 2023/11/10 08:53:21.124 [A] [main.go:29]  Lite: false
2023-11-10T16:53:21.124843342+08:00 2023/11/10 08:53:21.124 [A] [main.go:29]  Version: 2.2.4
2023/11/10 08:53:21.124 [A] [main.go:29]  Starting...
2023-11-10T16:53:21.124848649+08:00 2023/11/10 08:53:21.124 [I] [main.go:30]  the core was not running the last time v2rayA exited
2023-11-10T16:53:21.317990332+08:00 2023/11/10 08:53:21.317 [A] [index.go:116]  v2rayA is listening at http://127.0.0.1:2017
2023-11-10T16:53:21.318015942+08:00 2023/11/10 08:53:21.317 [A] [index.go:116]  v2rayA is listening at http://10.42.192.85:2017
2023-11-10T16:53:21.318018565+08:00 2023/11/10 08:53:21.317 [A] [index.go:116]  v2rayA is listening at http://[::1]:2017
2023-11-10T16:53:21.318020997+08:00 2023/11/10 08:53:21.317 [A] [index.go:116]  v2rayA is listening at http://[fe80::78d7:25ff:fedc:4b4c]:2017
2023-11-10T16:53:38.924186456+08:00 2023/11/10 08:53:38.923 [W] [v2ray.go:222]  IsDatetimeSynced: read udp 10.42.192.85:54291->203.107.6.88:123: i/o timeout
2023-11-10T16:53:39.120199036+08:00 2023/11/10 08:53:39.120 [I] [io.go:432]  V2Ray 5.4.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.20.2 linux/amd64)
2023-11-10T16:53:39.120262425+08:00 2023/11/10 08:53:39.120 [I] [io.go:432]  A unified platform for anti-censorship.
2023-11-10T16:53:42.626621131+08:00 2023/11/10 08:53:42.626 [W] [asm_amd64.s:1650]  v2ray-core: signal: killed
2023/11/10 08:53:42.718 [E] [connection.go:88]  failed to start v2ray-core: unexpected exiting: check the log for more information
2023/11/10 09:19:04.918 [I] [io.go:432]  V2Ray 5.4.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.20.2 linux/amd64)
2023-11-10T17:19:04.918393983+08:00 2023/11/10 09:19:04.918 [I] [io.go:432]  A unified platform for anti-censorship.
2023/11/10 09:19:08.621 [W] [asm_amd64.s:1650]  v2ray-core: signal: killed
2023/11/10 09:19:08.720 [E] [connection.go:88]  failed to start v2ray-core: unexpected exiting: check the log for more information
2023/11/10 09:28:53.071 [W] [v2ray.go:222]  IsDatetimeSynced: read udp 10.42.192.85:48008->203.107.6.88:123: i/o timeout
2023/11/10 09:28:53.220 [I] [io.go:432]  V2Ray 5.4.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.20.2 linux/amd64)
2023-11-10T17:28:53.220850277+08:00 2023/11/10 09:28:53.220 [I] [io.go:432]  A unified platform for anti-censorship.
2023/11/10 09:28:53.921 [E] [version.go:39]  failed to get latest version of GFWList: Get "https://hubmirror.v2raya.org/api/v2rayA/dist-v2ray-rules-dat/tags": dial tcp: lookup hubmirror.v2raya.org on 10.43.0.10:53: no such host

```

### v2rayA设置以及相关截图
