### ISSUE TITLE
docker v2raya 使用 network_mode: bridge 启动时，宿主机没有网络。

### ISSUE THREAD

**Issue by yuzhen1024** [v2rayA/v2rayA#1293]
类似 https://github.com/v2rayA/v2rayA/issues/156

但情况是完全没法联网，`ping baidu.com` 有效， `curl baidu.com` 无效。

启动参数:
```yaml
services:

  V2RayA:
    container_name: v2raya
    image: mzz2017/v2raya
    privileged: true
    environment:
      - V2RAYA_V2RAY_BIN=/usr/local/bin/xray
      - V2RAYA_LOG_FILE=/tmp/v2raya.log
      - TZ=Asia/Shanghai
    volumes:
      - /lib/module:/lib/modules:ro
      - /etc/v2raya:/etc/v2raya
#       - /etc/resolv.conf
    network_mode: bridge
    ports:
      - "127.0.0.1:2017:2017"
      - "20170-20173:20170-20173"
    restart: always
```

因为没有使用到映射的端口，所以日志里没有什么信息。
可以访问 `:2017` 配置页面。
