### ISSUE TITLE
docker host模式害人不浅？！Docker host mode is very harmful!

### ISSUE THREAD

**Issue by dingdangdog** [v2rayA/v2rayA#1390]
### Version, approach of installation, operating system

- V2rayA Version: 2.2.5.1
- Use Docker image: mzz2017/v2raya
- Ubuntu 24.04 LTS
- Docker version 26.1.0, build 9714adc
- Docker Compose version v2.27.0

```yaml
services:
  v2raya:
    container_name: v2raya
    image: mzz2017/v2raya
    restart: always
    privileged: true
    network_mode: host
    environment:
      - V2RAYA_LOG_FILE=/tmp/v2raya.log
      - V2RAYA_V2RAY_BIN=/usr/local/bin/v2ray
      - V2RAYA_NFTABLES_SUPPORT=off
      - IPTABLES_MODE=legacy
    volumes:
      - /lib/modules:/lib/modules:ro
      - /etc/resolv.conf:/etc/resolv.conf
      - /etc/v2raya:/etc/v2raya

```

### Description

这里就用中文了，快把我气死了。。。一直以为是docker的问题。。搞了几个小时！

> PS: 习惯使用`docekr-compose`管理配置，省心，所以几乎所有服务都用 `docker-compose` 启动的

使用上面的配置 `Docker Compose` 启动，`host` 模式，然后就导致其他不是 `host` 模式的 docker 容器全凉了！那些不是 `host` 模式的docker容器，全部无法通过局域网访问了！但是宿主机访问没问题。

如果我将那些不能访问的容器改为  `host` 模式，就会又能访问了。

当不能访问时，从局域网其他设备上看，IP+端口访问好像也被代理为了HTTPS？：

![image](https://github.com/v2rayA/v2rayA/assets/45959431/e5c1726e-ab1a-4639-a40e-f3b3d847e54a)

宿主机通过 `192.169.0.11:880` 访问也会出现这个不安全提示，但不会影响访问页面的加载和通信，只会提醒不安全，局域网其他设备访问时是直接无法访问！

当我发现其他容器使用 docker `host` 模式 就没问题时，差点就发到 `stackoverflow` 寻求帮助并疯狂吐槽 docker 了！！！还好突发奇想，尝试了下关掉 `v2raya` 重启 docker 服务，然后其他容器就恢复正常了！

现在我不确定是只有 docker 版本 `mzz2017/v2raya` 有这个问题，还是其他版本的 v2ray 也有这个问题！

当我停止v2raya的容器，并重启docekr后，局域网就可以访问了：

![image](https://github.com/v2rayA/v2rayA/assets/45959431/26501c3a-18ec-4e32-9559-86804cab78ca)

现在只好必要时再启动 `v2raya` 了。不知道有没有其他小伙伴遇到这个问题，发出来大家注意一下吧。

**当然还是感谢 `v2raya`  仓库的，基本功能还是挺好用的！**

不是很懂底层代理逻辑，弱弱问一句，这个问题能修复吗？

### Logs：

无，docker容器没有看到任何日志

### v2rayA setting and related screenshot
![image](https://github.com/v2rayA/v2rayA/assets/45959431/f4229fef-6f5a-40fc-bd25-3c878e3d2f58)
