### ISSUE TITLE
在docker的bridge下运行v2rayA能否实现透明代理？

### ISSUE THREAD

**Issue by SuZixiong** [v2rayA/v2rayA#503]
### 版本、安装方式、系统

1. 你在使用什么版本的v2rayA：1.5.7

3. 你通过什么方式安装v2rayA：docker

4. 你所使用的操作系统.Photon OS

### 描述问题：

在docker的bridge下运行v2rayA能否实现透明代理？

现在使用的docker compose如下

```
version: '3.3'

services:
  v2raya:
    restart: always
    privileged: true
    container_name: v2raya
    environment:
      - 'V2RAYA_ADDRESS=0.0.0.0:2017'
    volumes: 
      - '/lib/modules:/lib/modules'
      - '/etc/resolv.conf:/etc/resolv.conf'
      - '/etc/v2raya:/etc/v2raya'
    image: mzz2017/v2raya
    ports:
      - "2017:2017"
      - "38830:38830"
      - "32345:32345"
      - "32346:32346"
      - "20170-20172:20170-20172"


```
